Backend\Base\Models\Value:
    type: entity
    table: values
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        value:
            type: string
